name: ArtChemy
description: "시각장애인 미술관 도우미 앱"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.5+3
  http: ^0.13.5
  http_parser: ^4.0.2
  path_provider: ^2.1.5
  camera: ^0.10.6
  audioplayers: ^5.2.1
  permission_handler: ^11.0.0
  flutter_svg: ^2.0.9
  speech_to_text: ^7.0.0
  intl: ^0.18.0
  dio: ^5.8.0
  flutter_chat_ui: ^1.6.12
  flutter_chat_types: ^3.6.0
  flutter_tts: ^3.2.2
  web_socket_channel: ^2.4.0
  googleapis_auth: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  assets:
    - assets/profile.jpg
    - assets/picbot.png
    - assets/pictop.png
    - assets/kakao_icon.svg
    - assets/left_icon.svg
    - assets/right_icon.svg
    - assets/calender_icon.svg
    - assets/icon_userbox.svg
    - assets/icon_artchat.svg
    - assets/MIC_ICON.svg
    - assets/recommand_img.png
    - assets/vangogh.jpg
    - assets/river-hold-451408-v5-d6762db66906.json
    - assets/avatar.png
    - assets/guide_box.png
    - assets/loading_music.mp3

  fonts:
    - family: KoddiUD OnGothic
      fonts:
        - asset: assets/fonts/KoddiUDOnGothic-Regular.ttf
          weight: 400
        - asset: assets/fonts/KoddiUDOnGothic-Bold.ttf
          weight: 700
        - asset: assets/fonts/KoddiUDOnGothic-ExtraBold.ttf
          weight: 800

  uses-material-design: true

flutter_icons:
  android: true
  image_path: "assets/icon/app_icon.png"  # 로고 이미지 경로
  adaptive_icon_background: "#ffffff"  # 안드로이드 어댑티브 아이콘 배경색
#  adaptive_icon_foreground: "assets/app_icon.png"
